import type {
  NotificationTemplate,
  EmailRendered,
} from "../types";

/**
 * M3.9 / Q3.9a — Admin dispute escalation email.
 *
 * Fires when the mediator brain hands off to a human admin. Sent to the
 * `ADMIN_ESCALATION_EMAIL` destination configured in env. Email-only —
 * SMS/WhatsApp don't make sense for an admin handoff that needs full
 * context. The companion Slack webhook variant is dispatched separately
 * (raw HTTP, no template) by escalate.ts.
 */

export type AdminDisputeEscalationData = {
  disputeId: string;
  status: "escalated";
  reason: string;
  userId: string;
  userEmail?: string | null;
  userName?: string | null;
  contractorName?: string | null;
  complaint: string;
  disputedAmountCents: number | null;
  threadUrl: string | null;
};

export const adminDisputeEscalationTemplate: NotificationTemplate<AdminDisputeEscalationData> =
  {
    id: "admin.dispute.escalation.v1",
    contentType: "transactional",

    renderEmail: (data): EmailRendered => {
      const amountLine =
        data.disputedAmountCents != null
          ? `<p><strong>Disputed amount:</strong> $${(
              data.disputedAmountCents / 100
            ).toFixed(2)}</p>`
          : "";
      const contractorLine = data.contractorName
        ? `<p><strong>Contractor:</strong> ${data.contractorName}</p>`
        : "";
      const userLine = data.userName
        ? `<p><strong>Homeowner:</strong> ${data.userName}${
            data.userEmail ? ` &lt;${data.userEmail}&gt;` : ""
          }</p>`
        : data.userEmail
          ? `<p><strong>Homeowner:</strong> ${data.userEmail}</p>`
          : `<p><strong>Homeowner ID:</strong> ${data.userId}</p>`;
      const threadLink = data.threadUrl
        ? `<p style="margin-top:16px"><a href="${data.threadUrl}" style="color:#facc15">Open the full thread →</a></p>`
        : "";
      const subject = `[Dispute escalated] ${data.complaint.slice(0, 60)}${
        data.complaint.length > 60 ? "…" : ""
      }`;
      const html = `<!doctype html>
<html><body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:640px;margin:24px auto;line-height:1.5;color:#18181b">
  <div style="border-top:4px solid #f43f5e;padding-top:16px">
    <p style="margin:0;font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#52525b">iSolveUrProblems · Admin queue</p>
    <h2 style="margin:6px 0 0;font-size:22px">Dispute escalated — needs a human</h2>
  </div>
  <p><strong>Reason for escalation:</strong> ${data.reason}</p>
  ${userLine}
  ${contractorLine}
  ${amountLine}
  <div style="margin-top:16px;padding:12px;background:#fef2f2;border-left:4px solid #f43f5e">
    <p style="margin:0;font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#52525b">Opening complaint</p>
    <p style="margin:6px 0 0;white-space:pre-wrap">${data.complaint}</p>
  </div>
  <p style="margin-top:16px"><strong>Dispute ID:</strong> <code>${data.disputeId}</code></p>
  ${threadLink}
  <p style="margin-top:24px;font-size:12px;color:#52525b">This escalation was generated by 6 (mediator) per Q3.9a. The thread is paused on the homeowner side until an admin replies.</p>
</body></html>`;
      const text = `[Dispute escalated]

Reason: ${data.reason}
${data.userName ? `Homeowner: ${data.userName}${data.userEmail ? ` <${data.userEmail}>` : ""}` : data.userEmail ? `Homeowner: ${data.userEmail}` : `Homeowner ID: ${data.userId}`}
${data.contractorName ? `Contractor: ${data.contractorName}\n` : ""}${data.disputedAmountCents != null ? `Disputed amount: $${(data.disputedAmountCents / 100).toFixed(2)}\n` : ""}
Opening complaint:
${data.complaint}

Dispute ID: ${data.disputeId}
${data.threadUrl ? `Thread: ${data.threadUrl}\n` : ""}
— 6 (mediator)`;
      return { subject, html, text };
    },
  };

export default adminDisputeEscalationTemplate;
